export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';
export const CREATE_ORDER_REDIRECT_CLEAR = 'CREATE_ORDER_REDIRECT_CLEAR';
export const CREATE_ORDER_CLEAR = 'CREATE_ORDER_CLEAR';

export const SEND_ORDER_EMAIL_REQUEST = 'SEND_ORDER_EMAIL_REQUEST';
export const SEND_ORDER_EMAIL_SUCCESS = 'SEND_ORDER_EMAIL_SUCCESS';
export const SEND_ORDER_EMAIL_FAIL = 'SEND_ORDER_EMAIL_FAIL';
export const SEND_ORDER_EMAIL_CLEAR = 'SEND_ORDER_EMAIL_CLEAR';

export const USER_LIST_ORDERS_REQUEST = 'USER_LIST_ORDERS_REQUEST';
export const USER_LIST_ORDERS_SUCCESS = 'USER_LIST_ORDERS_SUCCESS';
export const USER_LIST_ORDERS_FAIL = 'USER_LIST_ORDERS_FAIL';
export const USER_LIST_ORDERS_CLEAR = 'USER_LIST_ORDERS_CLEAR';

export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAIL = 'GET_ORDER_FAIL';
export const GET_ORDER_CLEAR = 'GET_ORDER_CLEAR';

export const LIST_ORDERS_REQUEST = 'LIST_ORDERS_REQUEST';
export const LIST_ORDERS_SUCCESS = 'LIST_ORDERS_SUCCESS';
export const LIST_ORDERS_FAIL = 'LIST_ORDERS_FAIL';
export const LIST_ORDERS_CLEAR = 'LIST_ORDERS_CLEAR';

export const SET_PAID_REQUEST = 'SET_PAID_REQUEST';
export const SET_PAID_SUCCESS = 'SET_PAID_SUCCESS';
export const SET_PAID_FAIL = 'SET_PAID_FAIL';
export const SET_PAID_CLEAR = 'SET_PAID_CLEAR';

export const SET_DELIVERED_REQUEST = 'SET_DELIVERED_REQUEST';
export const SET_DELIVERED_SUCCESS = 'SET_DELIVERED_SUCCESS';
export const SET_DELIVERED_FAIL = 'SET_DELIVERED_FAIL';
export const SET_DELIVERED_CLEAR = 'SET_DELIVERED_CLEAR';

export const SET_CANCELED_REQUEST = 'SET_CANCELED_REQUEST';
export const SET_CANCELED_SUCCESS = 'SET_CANCELED_SUCCESS';
export const SET_CANCELED_FAIL = 'SET_CANCELED_FAIL';
export const SET_CANCELED_CLEAR = 'SET_CANCELED_CLEAR';
