export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';
export const GET_PRODUCTS_CLEAR = 'GET_PRODUCTS_CLEAR';

export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL';
export const GET_PRODUCT_CLEAR = 'GET_PRODUCT_CLEAR';

export const CREATE_REVIEW_REQUEST = 'CREATE_REVIEW_REQUEST';
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS';
export const CREATE_REVIEW_FAIL = 'CREATE_REVIEW_FAIL';
export const CREATE_REVIEW_CLEAR = 'CREATE_REVIEW_CLEAR';

export const UPDATE_REVIEW_REQUEST = 'UPDATE_REVIEW_REQUEST';
export const UPDATE_REVIEW_SUCCESS = 'UPDATE_REVIEW_SUCCESS';
export const UPDATE_REVIEW_FAIL = 'UPDATE_REVIEW_FAIL';
export const UPDATE_REVIEW_CLEAR = 'UPDATE_REVIEW_CLEAR';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';
export const DELETE_PRODUCT_CLEAR = 'DELETE_PRODUCT_CLEAR';

export const SET_PRODUCT_STOCK_REQUEST = 'SET_PRODUCT_STOCK_REQUEST';
export const SET_PRODUCT_STOCK_SUCCESS = 'SET_PRODUCT_STOCK_SUCCESS';
export const SET_PRODUCT_STOCK_FAIL = 'SET_PRODUCT_STOCK_FAIL';
export const SET_PRODUCT_STOCK_CLEAR = 'SET_PRODUCT_STOCK_CLEAR';
