export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SIGNUP_CLEAR = 'SIGNUP_CLEAR';

export const SEND_VERIFY_USER_REQUEST = 'SEND_VERIFY_USER_REQUEST';
export const SEND_VERIFY_USER_SUCCESS = 'SEND_VERIFY_USER_SUCCESS';
export const SEND_VERIFY_USER_FAIL = 'SEND_VERIFY_USER_FAIL';
export const SEND_VERIFY_USER_CLEAR = 'SEND_VERIFY_USER_CLEAR';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_ALERT = 'LOGIN_ALERT';
export const LOGIN_CLEAR = 'LOGIN_CLEAR';

export const USER_DATA_REQUEST = 'USER_DATA_REQUEST';
export const USER_DATA_SUCCESS = 'USER_DATA_SUCCESS';
export const USER_DATA_FAIL = 'USER_DATA_FAIL';
export const USER_DATA_CLEAR = 'USER_DATA_CLEAR';

export const VERIFY_USER_REQUEST = 'VERIFY_USER_REQUEST';
export const VERIFY_USER_SUCCESS = 'VERIFY_USER_SUCCESS';
export const VERIFY_USER_FAIL = 'VERIFY_USER_FAIL';
export const VERIFY_USER_CLEAR = 'VERIFY_USER_CLEAR';
